---
- name: Install beats pre-req software
  ansible.builtin.apt:
    name: "{{ item }}"
  loop: "{{ beats_client_beats_prereq }}"

- name: Add Beats apt repository.
  ansible.builtin.deb822_repository:
    name: elastic-beats
    types:
      - deb
    uris: "{{ beats_client_elastic_repo_uri }}"
    suites:
      - stable
    components:
      - main
    signed_by: "{{ beats_client_elastic_gpg_key_url }}"
    state: present
  register: beats_elastic_repo

- name: Update apt cache after adding Beats repository.
  ansible.builtin.apt:
    update_cache: yes
  when: beats_elastic_repo.changed

- name: Install beat packages.
  ansible.builtin.apt:
    name: "{{ item }}={{ beats_client_version }}"
    state: present
    allow_downgrade: yes
  loop: "{{ beats_client_beats_packages }}"
