---
- name: restart filebeat
  become: yes
  ansible.builtin.service:
    name: filebeat
    state: restarted

- name: restart packetbeat
  become: yes
  ansible.builtin.service:
    name: topbeat
    state: restarted

- name: restart heartbeat
  become: yes
  ansible.builtin.service:
    name: heartbeat
    state: restarted

- name: restart metricbeat
  become: yes
  ansible.builtin.service:
    name: metricbeat
    state: restarted
